name: lsst_distrib_cvmfs CI

on:
  # Manual trigger
  workflow_dispatch:

jobs:
  ubuntu-minimal:
    runs-on: ubuntu-latest
    steps:
    - uses: cvmfs-contrib/github-action-cvmfs@v4
      with:
        cvmfs_repositories: 'sw.lsst.eu'
    - name: Test CernVM-FS
      run: |
        cat /etc/cvmfs/default.local
        ls /cvmfs
        ls /cvmfs/sw.lsst.eu
        
