name: lsst_distrib_cvmfs CI

on:
  # Manual trigger
  workflow_dispatch:

jobs:
  ubuntu-minimal:
    runs-on: ubuntu-latest
    steps:
    - uses: cvmfs-contrib/github-action-cvmfs@v4
      with:
        cvmfs_repositories: 'sw.lsst.eu'
    - name: Test CernVM-FS
      run: |
        echo "running pwd -P"
        pwd -P
        echo "running ls ./"
        ls ./
        echo "running ls ../"
        ls ../
        echo "running ls /"
        ls /
        echo "cat /etc/cvmfs/default.local"
        cat /etc/cvmfs/default.local
        echo "running ls /cvmfs"
        ls /cvmfs
        echo "running cvmfs_config showconfig -s sw.lsst.eu"
        cvmfs_config showconfig -s sw.lsst.eu
