name: minimal cvmfs example with sw.lsst.eu

on:
  # Manual trigger
  workflow_dispatch:

jobs:
  ubuntu-minimal:
    runs-on: ubuntu-latest
    steps:
    - uses: cvmfs-contrib/github-action-cvmfs@v4
      with: 
        cvmfs_repositories: 'sw.lsst.eu'
    - name: Test CernVM-FS
      run: |
        ls /cvmfs/sft.cern.ch/
        ls /cvmfs
